spring.application.name=uniMed

# Server configuration
server.port=8000

# Database configuration
spring.datasource.url=jdbc:mysql://localhost:3306/uni_health
spring.datasource.username=root
spring.datasource.password=Rasel2003
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# Hibernate settings
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect


# Docker compose configuration
spring.docker.compose.enabled=false
spring.ai.retry.max-attempts=10
spring.ai.retry.backoff.initial-interval=2000
spring.ai.retry.backoff.multiplier=5
spring.ai.retry.backoff.max-interval=180000
spring.ai.retry.on-client-errors=false
spring.ai.retry.exclude-on-http-codes=
spring.ai.retry.on-http-codes=
# JPA configuration
spring.jpa.hibernate.ddl-auto=update
spring.ai.vertex.ai.gemini.project-id=52496785404
spring.ai.vertex.ai.gemini.location=LOCATION
spring.ai.vertex.ai.gemini.chat.options.model=vertex-pro-vision
spring.ai.vertex.ai.gemini.chat.options.temperature=0.5
spring.jpa.show-sql=true
logging.level.org.springframework.security=DEBUG
spring.ai.openai.api-key=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
spring.ai.openai.chat.options.model=gpt-3.5-turbo
spring.ai.openai.chat.options.temperature=0.7
openai.api.key=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
# JWT secret key (if using JWT for security)
jwt.secret=aljjpp90345-jag3432safds423gqeq23234WGRSRT
logging.level.org.apache.coyote.http11.Http11Processor=DEBUG


# Multipart file configuration
spring.servlet.multipart.enabled=true
spring.servlet.multipart.location=public/
file.upload-dir=uploads
server.url=http://localhost:8000